sudo: required
services:
  - docker

before_install:
  - docker build -t akowalsk/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run akowalsk/react-test npm test -- --coverage

after_success:
  - docker build -t akowalsk/multi-client -f ./client
  - docker build -t akowalsk/multi-nginx -f ./nginx
  - docker build -t akowalsk/multi-server -f ./server
  - docker build -t akowalsk/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akowalsk/multi-client
  - docker push akowalsk/multi-nginx
  - docker push akowalsk/multi-server
  - docker push akowalsk/multi-worker