sudo: required
services:
  - docker

before_install:
  - docker build -t akowalsk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run akowalsk/react-test npm test -- --coverage

after_success:
  - docker build -t akowalsk/multi-client ./client
  - docker build -t akowalsk/multi-nginx ./nginx
  - docker build -t akowalsk/multi-server ./server
  - docker build -t akowalsk/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akowalsk/multi-client
  - docker push akowalsk/multi-nginx
  - docker push akowalsk/multi-server
  - docker push akowalsk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-953540070277"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"